<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FrankBr.Rendering</AssemblyName>
    <RootNamespace>FrankBr.Rendering</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\\FrankBr.Core\\FrankBr.Core.csproj" />
    <ProjectReference Include="..\\FrankBr.Canvas\\FrankBr.Canvas.csproj" />
  </ItemGroup>
</Project>
